credentials:
  usernames:
    admin:
      name: Administrador Urbano
      password: "$2b$12$D1QjxO2jcUe8FUiTRd5KwOfrbUH3ty9fhhh8eETZA/qSO.oQb6Gle"
      email: wm@wmsolucoes.eng.br
      logged_in: False
cookie:
  expiry_days: 30
  key: "chave_secreta_urbano_sistema"
  name: "urbano_cookie"
preauthorized:
  emails: []