name: Disparo Diario de Emails

on:
  schedule:
    - cron: '0 11 * * *'
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  run-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: INSTALAÇÃO LEVE (SEM PDF) - VERSÃO FINAL
        # Mudei o nome acima para você conferir no log se atualizou
        run: |
          python -m pip install --upgrade pip
          # Instalamos MANUALMENTE apenas o que o robô precisa.
          # NUNCA use 'pip install -r requirements.txt' aqui se ele tiver xhtml2pdf.
          pip install streamlit firebase-admin google-generativeai pandas bcrypt toml

      - name: Executar Script
        env:
          FIREBASE_KEY_JSON: ${{ secrets.FIREBASE_KEY_JSON }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python scheduler.py
# Atualizacao Forcada