[client]
showErrorDetails = false
toolbarMode = "viewer"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50